# Creating the adjacency matrices 

# Test Cell - Very Simple Example 

In [30]:
# Create a threshold variable 
thres <- .5

# Create sample matrix to calculate 
B = matrix(c(1, 2, 3, 9, 3, 4, 5, 9, 1, 6, 3, 9), nrow=4, ncol=3)  

C = data.frame(B)

# Change to data frame, doesn't really matter but I use data frames in  my calculations below
print('Example Dataframe');

C

# Create some data frame specific vars
numRats <- ncol(C)
numObs <- nrow(C)

# Create matrices 
incidence <- diag(numObs, numRats)
unthresholded <- diag(0, numRats)
thresholded <- diag(0, numRats)

print('All data Structures before calculation');

print('Incidence dataframe before calculation')
incidence 
print('Unthresholded dataframe before calculation')
unthresholded
print('Thresholded dataframe before calculation')
thresholded

# Fill incidence and thresholded matrices - Filling both the upper half of the square matrix to utilize as a adjacency matrix 
for (i in 1:(numRats-1)) {
    for (j in i:numRats) {
      # First example iteration will compare ALL of column 1 with column 1 Create True and False values 
      incidence[i,j] <- incidence[j,i] <- sum(B[,i] == B[,j])
      unthresholded[i,j] <- unthresholded[j,i] <- incidence[i,j]/numObs #>= thres
      thresholded[i,j] <- thresholded[j,i] <- incidence[i,j]/numObs >= thres
    }
}

# Alter the datafram diagonal of the unthresholded and thresholded matrices to better perform social network calcs 
diag(unthresholded) = 0
diag(thresholded) = 0

print('All data Structures after calculation')

print('Incidence dataframe after calculation')
incidence 
print('Unthresholded dataframe after calculation')
unthresholded
print('Thresholded dataframe after calculation')
thresholded



[1] "Example Dataframe"


X1 X2 X3
1 1  3  1 
2 2  4  6 
3 3  5  3 
4 9  9  9

[1] "All data Structures before calculation"
[1] "Incidence dataframe before calculation"


[,1] [,2] [,3]
[1,] 4    0    0   
[2,] 0    4    0   
[3,] 0    0    4

[1] "Unthresholded dataframe before calculation"


[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0   
[3,] 0    0    0

[1] "Thresholded dataframe before calculation"


[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0   
[3,] 0    0    0

[1] "All data Structures after calculation"
[1] "Incidence dataframe after calculation"


[,1] [,2] [,3]
[1,] 4    1    3   
[2,] 1    4    1   
[3,] 3    1    4

[1] "Unthresholded dataframe after calculation"


[,1] [,2] [,3]
[1,] 0.00 0.25 0.75
[2,] 0.25 0.00 0.25
[3,] 0.75 0.25 0.00

[1] "Thresholded dataframe after calculation"


[,1] [,2] [,3]
[1,] 0    0    1   
[2,] 0    0    0   
[3,] 1    0    0

# Real Rat Data Test Example - Window 728

In [42]:
# Establish working directory
workingDir <- "/home/zackymo/Desktop/Sample"
setwd(workingDir)

# Next Line for debugging purposes 
file <- "5-14-2014streamW728PPstate.txt"

# This statement automagically reads the data into a dataframe 
df <- read.table(file)

# Create some data frame specific vars
numRats <- ncol(df)
numObs <- nrow(df)

# Create matrices 
incidence <- diag(numObs, numRats)
unthresholded <- diag(0, numRats)
thresholded <- diag(0, numRats)

# Logging Info 
print('All data Structures before calculation');

print('Incidence dataframe before calculation')
head(incidence) 
print('Unthresholded dataframe before calculation')
head(unthresholded)
print('Thresholded dataframe before calculation')
head(thresholded)

# Fill incidence and thresholded matrices 
for (i in 1:(numRats-1)) {
    for (j in i:numRats) {
      # First example iteration will compare ALL of column 1 with column 1, 
      # generate True and False values for these columns, then count the True and False values and put that into the 
      # designated row in the incidence matrix, the next iteration will compare ALL of column 1 with column 2 
      incidence[i,j] <- incidence[j,i] <- sum(df[,i] == df[,j])
      unthresholded[i,j] <- unthresholded[j,i] <- incidence[i,j]/numObs #>= thres
      thresholded[i,j] <- thresholded[j,i] <- incidence[i,j]/numObs >= thres
    }
}

# Alter the datafram diagonal of the unthresholded and thresholded matrices to better perform social network calcs 
diag(unthresholded) = 0
diag(thresholded) = 0

print('All data Structures after calculation')

print('Incidence dataframe after calculation')
head(incidence) 
print('Unthresholded dataframe after calculation')
head(unthresholded)
print('Thresholded dataframe after calculation')
head(thresholded)


[1] "All data Structures before calculation"
[1] "Incidence dataframe before calculation"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 903    0    0    0    0    0  0    0    0    0     ⋯     0     0     0    
[2,]   0  903    0    0    0    0  0    0    0    0     ⋯     0     0     0    
[3,]   0    0  903    0    0    0  0    0    0    0     ⋯     0     0     0    
[4,]   0    0    0  903    0    0  0    0    0    0     ⋯     0     0     0    
[5,]   0    0    0    0  903    0  0    0    0    0     ⋯     0     0     0    
[6,]   0    0    0    0    0  903  0    0    0    0     ⋯     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 0     0     0     0     0     0     0    
[2,] 0     0     0     0     0     0     0    
[3,] 0     0     0     0     0     0     0    
[4,] 0     0     0     0     0     0     0    
[5,] 0     0     0     0     0     0     0    
[6,] 0     0     0     0     0     0     0

[1] "Unthresholded dataframe before calculation"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
[2,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
[3,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
[4,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
[5,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
[6,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 0     0     0     0     0     0     0    
[2,] 0     0     0     0     0     0     0    
[3,] 0     0     0     0     0     0     0    
[4,] 0     0     0     0     0     0     0    
[5,] 0     0     0     0     0     0     0    
[6,] 0     0     0     0     0     0     0

[1] "Thresholded dataframe before calculation"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
[2,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
[3,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
[4,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
[5,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
[6,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 0     0     0     0     0     0     0    
[2,] 0     0     0     0     0     0     0    
[3,] 0     0     0     0     0     0     0    
[4,] 0     0     0     0     0     0     0    
[5,] 0     0     0     0     0     0     0    
[6,] 0     0     0     0     0     0     0

[1] "All data Structures after calculation"
[1] "Incidence dataframe after calculation"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 903  510    0  703   16  703  175  703   0   703   ⋯       0     0     0  
[2,] 510  903  287  505  293  505  462  505   0   505   ⋯     287   287   287  
[3,]   0  287  903    0  381    0  649    0   0     0   ⋯     903   903   903  
[4,] 703  505    0  903   16  903  175  903   0   903   ⋯       0     0     0  
[5,]  16  293  381   16  903   16  387   16  28    16   ⋯     381   381   381  
[6,] 703  505    0  903   16  903  175  903   0   903   ⋯       0     0     0  
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 703     0   629   259   703     0     0  
[2,] 505   287   431   204   505   287   287  
[3,]   0   903     0   244     0   903   903  
[4,] 903     0   829   152   903     0     0  
[5,]  16   381    16     0    16   381   381  
[6,] 903     0   829   152   903     0     0

[1] "Unthresholded dataframe after calculation"


[,1]       [,2]      [,3]      [,4]       [,5]       [,6]       [,7]     
[1,] 0.00000000 0.5647841 0.0000000 0.77851606 0.01771872 0.77851606 0.1937984
[2,] 0.56478405 0.0000000 0.3178295 0.55924695 0.32447398 0.55924695 0.5116279
[3,] 0.00000000 0.3178295 0.0000000 0.00000000 0.42192691 0.00000000 0.7187154
[4,] 0.77851606 0.5592470 0.0000000 0.00000000 0.01771872 1.00000000 0.1937984
[5,] 0.01771872 0.3244740 0.4219269 0.01771872 0.00000000 0.01771872 0.4285714
[6,] 0.77851606 0.5592470 0.0000000 1.00000000 0.01771872 0.00000000 0.1937984
     [,8]       [,9]       [,10]      [,11] [,12]     [,13]     [,14]    
[1,] 0.77851606 0.00000000 0.77851606 ⋯     0.0000000 0.0000000 0.0000000
[2,] 0.55924695 0.00000000 0.55924695 ⋯     0.3178295 0.3178295 0.3178295
[3,] 0.00000000 0.00000000 0.00000000 ⋯     1.0000000 1.0000000 1.0000000
[4,] 1.00000000 0.00000000 1.00000000 ⋯     0.0000000 0.0000000 0.0000000
[5,] 0.01771872 0.03100775 0.01771872 ⋯     0.4219269 0.4219269 0.4219269
[6,] 1.00000000 0.00000000 1.00000000 ⋯     0.0000000 0.0000000 0.0000000
     [,15]      [,16]     [,17]      [,18]     [,19]      [,20]     [,21]    
[1,] 0.77851606 0.0000000 0.69656700 0.2868217 0.77851606 0.0000000 0.0000000
[2,] 0.55924695 0.3178295 0.47729790 0.2259136 0.55924695 0.3178295 0.3178295
[3,] 0.00000000 1.0000000 0.00000000 0.2702104 0.00000000 1.0000000 1.0000000
[4,] 1.00000000 0.0000000 0.91805094 0.1683278 1.00000000 0.0000000 0.0000000
[5,] 0.01771872 0.4219269 0.01771872 0.0000000 0.01771872 0.4219269 0.4219269
[6,] 1.00000000 0.0000000 0.91805094 0.1683278 1.00000000 0.0000000 0.0000000

[1] "Thresholded dataframe after calculation"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 0    1    0    1    0    1    0    1    0    1     ⋯     0     0     0    
[2,] 1    0    0    1    0    1    1    1    0    1     ⋯     0     0     0    
[3,] 0    0    0    0    0    0    1    0    0    0     ⋯     1     1     1    
[4,] 1    1    0    0    0    1    0    1    0    1     ⋯     0     0     0    
[5,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0     0    
[6,] 1    1    0    1    0    0    0    1    0    1     ⋯     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 1     0     1     0     1     0     0    
[2,] 1     0     0     0     1     0     0    
[3,] 0     1     0     0     0     1     1    
[4,] 1     0     1     0     1     0     0    
[5,] 0     0     0     0     0     0     0    
[6,] 1     0     1     0     1     0     0

# Dr. Kress Calcs  - My unthresholded data frame after calcs is different from your  (yours is ontop, and mine is seen below) - Would you mind verifying your matrix calculation

In [48]:
# Read in the result CSV Dr. Kress gave me 

df = read.csv('/home/zackymo/Desktop/DegasAdjTimeW728.csv')

print('Dr. Kress Calcs')
head(df)

print('Zachs Calcs')
head(unthresholded)

[1] "Dr. Kress Calcs"


X V1          V2        V3        V4          V5          V6         
1 1 0.000000000 0.6647222 0.0000000 0.826694444 0.008025556 0.826694444
2 2 0.664722222 0.0000000 0.1974361 0.650194444 0.201388889 0.650194444
3 3 0.000000000 0.1974361 0.0000000 0.000000000 0.333500000 0.000000000
4 4 0.826694444 0.6501944 0.0000000 0.000000000 0.008025556 1.000000000
5 5 0.008025556 0.2013889 0.3335000 0.008025556 0.000000000 0.008025556
6 6 0.826694444 0.6501944 0.0000000 1.000000000 0.008025556 0.000000000
  V7        V8          V9         ⋯ V50       V51       V52       V53        
1 0.1836778 0.826694444 0.00000000 ⋯ 0.0000000 0.0000000 0.0000000 0.826694444
2 0.3811111 0.650194444 0.00000000 ⋯ 0.1974361 0.1974361 0.1974361 0.650194444
3 0.6620278 0.000000000 0.00000000 ⋯ 1.0000000 1.0000000 1.0000000 0.000000000
4 0.1836778 1.000000000 0.00000000 ⋯ 0.0000000 0.0000000 0.0000000 1.000000000
5 0.3344722 0.008025556 0.01007083 ⋯ 0.3335000 0.3335000 0.3335000 0.008025556
6 0.1836778 1.000000000 0.00000000 ⋯ 0.0000000 0.0000000 0.0000000 1.000000000
  V54       V55         V56       V57         V58       V59      
1 0.0000000 0.808111111 0.4026389 0.826694444 0.0000000 0.0000000
2 0.1974361 0.631583333 0.3134722 0.650194444 0.1974361 0.1974361
3 1.0000000 0.000000000 0.3425000 0.000000000 1.0000000 1.0000000
4 0.0000000 0.981388889 0.2660500 1.000000000 0.0000000 0.0000000
5 0.3335000 0.008025556 0.0000000 0.008025556 0.3335000 0.3335000
6 0.0000000 0.981388889 0.2660500 1.000000000 0.0000000 0.0000000

[1] "Zachs Calcs"


[,1]       [,2]      [,3]      [,4]       [,5]       [,6]       [,7]     
[1,] 0.00000000 0.5647841 0.0000000 0.77851606 0.01771872 0.77851606 0.1937984
[2,] 0.56478405 0.0000000 0.3178295 0.55924695 0.32447398 0.55924695 0.5116279
[3,] 0.00000000 0.3178295 0.0000000 0.00000000 0.42192691 0.00000000 0.7187154
[4,] 0.77851606 0.5592470 0.0000000 0.00000000 0.01771872 1.00000000 0.1937984
[5,] 0.01771872 0.3244740 0.4219269 0.01771872 0.00000000 0.01771872 0.4285714
[6,] 0.77851606 0.5592470 0.0000000 1.00000000 0.01771872 0.00000000 0.1937984
     [,8]       [,9]       [,10]      [,11] [,12]     [,13]     [,14]    
[1,] 0.77851606 0.00000000 0.77851606 ⋯     0.0000000 0.0000000 0.0000000
[2,] 0.55924695 0.00000000 0.55924695 ⋯     0.3178295 0.3178295 0.3178295
[3,] 0.00000000 0.00000000 0.00000000 ⋯     1.0000000 1.0000000 1.0000000
[4,] 1.00000000 0.00000000 1.00000000 ⋯     0.0000000 0.0000000 0.0000000
[5,] 0.01771872 0.03100775 0.01771872 ⋯     0.4219269 0.4219269 0.4219269
[6,] 1.00000000 0.00000000 1.00000000 ⋯     0.0000000 0.0000000 0.0000000
     [,15]      [,16]     [,17]      [,18]     [,19]      [,20]     [,21]    
[1,] 0.77851606 0.0000000 0.69656700 0.2868217 0.77851606 0.0000000 0.0000000
[2,] 0.55924695 0.3178295 0.47729790 0.2259136 0.55924695 0.3178295 0.3178295
[3,] 0.00000000 1.0000000 0.00000000 0.2702104 0.00000000 1.0000000 1.0000000
[4,] 1.00000000 0.0000000 0.91805094 0.1683278 1.00000000 0.0000000 0.0000000
[5,] 0.01771872 0.4219269 0.01771872 0.0000000 0.01771872 0.4219269 0.4219269
[6,] 1.00000000 0.0000000 0.91805094 0.1683278 1.00000000 0.0000000 0.0000000